# Generated by Django 5.0.4 on 2024-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMDealInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_db', models.DateTimeField(auto_now_add=True)),
                ('crm_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=255)),
                ('status_name', models.CharField(max_length=255)),
                ('status_changed_at', models.DateTimeField()),
                ('created_at_crm', models.DateTimeField()),
                ('updated_at_crm', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('support_operator_id', models.CharField(max_length=255)),
                ('support_first_name', models.CharField(max_length=255)),
                ('support_last_name', models.CharField(max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('building', models.CharField(blank=True, max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('order_confirmation_date', models.DateTimeField()),
                ('substatus', models.CharField(blank=True, max_length=255)),
                ('the_courier_was_polite', models.CharField(blank=True, max_length=255)),
                ('was_the_client_at_the_address', models.CharField(blank=True, max_length=255)),
                ('did_the_courier_arrive', models.CharField(blank=True, max_length=255)),
                ('was_the_sms_from_courier', models.CharField(blank=True, max_length=255)),
                ('original_order_id', models.CharField(blank=True, max_length=255)),
                ('original_operator_order', models.CharField(blank=True, max_length=255)),
                ('working_days', models.CharField(blank=True, max_length=255)),
                ('comment_after_call', models.CharField(blank=True, max_length=255)),
                ('original_delivery_status', models.CharField(blank=True, max_length=255)),
                ('original_status_cs', models.CharField(blank=True, max_length=255)),
                ('original_order_list', models.CharField(blank=True, max_length=255)),
                ('customer_address', models.CharField(blank=True, max_length=255)),
                ('original_track_number', models.CharField(blank=True, max_length=255)),
                ('comment_for_cs', models.CharField(blank=True, max_length=255)),
                ('delivery_status', models.CharField(blank=True, max_length=255)),
                ('status_cs', models.CharField(blank=True, max_length=255)),
                ('track_number', models.CharField(blank=True, max_length=255)),
                ('original_comment_for_cs', models.CharField(blank=True, max_length=255)),
                ('timezoneOffset', models.CharField(blank=True, max_length=255)),
                ('exception', models.CharField(blank=True, max_length=255)),
                ('reminder_timer', models.DateTimeField()),
                ('reminder_comment', models.CharField(blank=True, max_length=255)),
                ('source_uri', models.CharField(blank=True, max_length=255)),
                ('source_refererUri', models.CharField(blank=True, max_length=255)),
                ('source_ip', models.CharField(blank=True, max_length=255)),
                ('source_utm_source', models.CharField(blank=True, max_length=255)),
                ('source_utm_medium', models.CharField(blank=True, max_length=255)),
                ('source_utm_campaign', models.CharField(blank=True, max_length=255)),
                ('source_utm_content', models.CharField(blank=True, max_length=255)),
                ('source_utm_term', models.CharField(blank=True, max_length=255)),
                ('source_subid_1', models.CharField(blank=True, max_length=255)),
                ('source_subid_2', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
