# Generated by Django 5.0.4 on 2024-05-21 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sku_title', models.CharField(max_length=255)),
                ('sku_id', models.CharField(max_length=255)),
                ('item_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Deal', to='fulfilment.crmdealinfo')),
            ],
        ),
    ]
