# Generated by Django 5.0.4 on 2024-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0002_crmdealitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentCRMConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('crm_title', models.CharField(max_length=255)),
                ('crm_product_title', models.CharField(max_length=255)),
                ('crm_product_id', models.IntegerField()),
                ('ff_product_code', models.IntegerField()),
                ('ff_title', models.CharField(max_length=255)),
                ('ff_login', models.CharField(max_length=255)),
                ('ff_subdomain', models.CharField(max_length=255)),
            ],
        ),
    ]
