# Generated by Django 5.0.4 on 2024-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0003_fulfillmentcrmconnections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulfillmentcrmconnections',
            old_name='country',
            new_name='banned_country',
        ),
        migrations.AddField(
            model_name='fulfillmentcrmconnections',
            name='working_country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
