# Generated by Django 5.0.4 on 2024-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0004_rename_country_fulfillmentcrmconnections_banned_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inner_id', models.CharField(max_length=255)),
            ],
        ),
    ]
