# Generated by Django 5.0.4 on 2024-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0005_fulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='login',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
