# Generated by Django 5.0.4 on 2024-05-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0006_fulfillment_login_fulfillment_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillmentcrmconnections',
            name='ff_subdomain',
        ),
        migrations.RemoveField(
            model_name='fulfillmentcrmconnections',
            name='ff_title',
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='api_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
