# Generated by Django 5.0.4 on 2024-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0007_remove_fulfillmentcrmconnections_ff_subdomain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentcrmconnections',
            name='crm_product_id',
            field=models.CharField(max_length=255),
        ),
    ]
