# Generated by Django 5.0.4 on 2024-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0009_alter_fulfillmentcrmconnections_ff_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadvertexAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_title', models.CharField(max_length=255)),
                ('crm_id', models.IntegerField()),
                ('lv_api_token', models.CharField(max_length=350)),
                ('lv_link', models.CharField(max_length=255)),
                ('lv_prefix', models.CharField(max_length=255)),
            ],
        ),
    ]
