# Generated by Django 5.0.4 on 2024-05-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0010_leadvertexapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_title', models.CharField(max_length=255, unique=True)),
                ('crm_id', models.IntegerField()),
                ('lv_api_token', models.CharField(max_length=350)),
                ('lv_link', models.CharField(max_length=255)),
                ('lv_prefix', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LeadvertexAPI',
        ),
    ]
