# Generated by Django 5.0.4 on 2024-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0011_crminterface_delete_leadvertexapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMStatusIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_title', models.CharField(max_length=255)),
                ('status_title', models.CharField(max_length=255)),
                ('status_id', models.IntegerField()),
            ],
        ),
    ]
