# Generated by Django 5.0.4 on 2024-06-04 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0012_crmstatusids'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentFollowingStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.IntegerField()),
                ('ff_order_number', models.CharField(max_length=255)),
                ('ff_status_id', models.IntegerField()),
                ('ff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fulfillment', to='fulfilment.fulfillment')),
            ],
        ),
    ]
