# Generated by Django 5.0.4 on 2024-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0014_alter_fulfillmentfollowingstatuses_ff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillmentfollowingstatuses',
            name='ff_status_id',
        ),
        migrations.AddField(
            model_name='fulfillmentfollowingstatuses',
            name='ff_status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
