# Generated by Django 5.0.4 on 2024-06-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0018_alter_crmdealinfo_cart_total_in_euros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmdealitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='crmdealitem',
            name='title',
        ),
    ]
