# Generated by Django 5.0.4 on 2024-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0020_fulfillmentfollowingstatuses_is_status_updated_in_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentfollowingstatuses',
            name='is_status_updated_in_crm',
            field=models.BooleanField(default=True),
        ),
    ]
