# Generated by Django 5.0.4 on 2024-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0021_alter_fulfillmentfollowingstatuses_is_status_updated_in_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentfollowingstatuses',
            name='ff_status',
            field=models.TextField(blank=True),
        ),
    ]
